version: '3.8'

networks:
  cloud-net:
    name: cloud-net

volumes:
  postgres-data:

services:
  web-frontend-server:
    build: ./web-frontend-server
    image: hotensv/web:dev
    container_name: web-frontend-server
    ports:
      - "8080:80"
    networks:
      - cloud-net
    restart: unless-stopped

  application-backend-server:
    build: ./application-backend-server
    image: hotensv/app:dev
    container_name: application-backend-server
    depends_on:
      - relational-database-server
    environment:
      DATABASE_URL: postgresql://postgres:postgres@relational-database-server:5432/minicloud
      OIDC_AUDIENCE: myapp
    ports:
      - "8085:8081"
    networks:
      - cloud-net
    restart: unless-stopped

  relational-database-server:
    image: postgres:16-alpine
    container_name: relational-database-server
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
    networks:
      - cloud-net
    restart: unless-stopped